version: "3.8"

services:
  Foxy.PersonalBlog:
    image: foxy-personal-blog
    container_name: foxy-personal-blog-container
    ports:
      - "8000:8000"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
