services:
  app:
    container_name: esratansuk-personal-website
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "44397:3000"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - compose-network
    dns:
      - 8.8.8.8

networks:
  compose-network:
    external: true
